import os
import pickle
import subprocess

class WorldLevelNode:
    def __init__(self, is_leaf=False, split_feature=None, split_value=None, classification=None):
        self.split_feature = split_feature    
        self.split_value = split_value        
        self.is_leaf = is_leaf
        self.classification = classification  
        self.tb = None                        
        self.fb = None                        

class ParthoodInferencePipeline:
    def __init__(self):
        self.model_dir = "/home/rsherman/projects/SMT-ILP/ZeroVRAM/story_intake_directory/pickled_models"
        self.root_dir = "/home/rsherman/projects/SMT-ILP/ZeroVRAM/Popper-main/examples"
        self.dcg_path = "/home/rsherman/projects/SMT-ILP/ZeroVRAM/popper_workspaces/linguistic_tier1/parser_tier1.pl"
        
        with open(os.path.join(self.model_dir, "level6_parthood_ontology.pkl"), "rb") as f:
            self.t6 = pickle.load(f)

    def query_prolog_parthood(self, subject, dimension):
        prolog_query = f"consult('{self.dcg_path}'), (part_of({subject}, {dimension}, Value) -> write(Value) ; write('unknown')), halt."
        try:
            result = subprocess.run(
                ["swipl", "-q", "-g", prolog_query],
                capture_output=True, text=True, timeout=3
            )
            return result.stdout.strip()
        except Exception:
            return "unknown"

    def evaluate_tree(self, node, feature_vector):
        if node is None: return "unknown"
        if node.is_leaf: 
            raw = str(node.classification).lower().strip()
            return raw.replace("[", "").replace("]", "").replace("'", "")
        val = feature_vector.get(node.split_feature, "unknown")
        if str(val) == str(node.split_value): 
            return self.evaluate_tree(node.tb, feature_vector)
        return self.evaluate_tree(node.fb, feature_vector)

    def run_inference(self):
        print("=" * 95)
        print("🔮 INTENSIONAL INFERENCE SUITE: EVALUATING PARTHOOD OVERLAP SYSTEM MATRIX")
        print("=" * 95)
        
        subjects = ["judith", "moses", "david", "paul", "joseph", "gideon", "peter"]
        t6_facts = []

        for sub in subjects:
            # 🚨 QUERIES ALL ACTIVE DIMENSIONS EXTRACTED VIA THE PROLOG PARSER
            features = {
                "syntax": self.query_prolog_parthood(sub, "syntax"),
                "abstract_type": self.query_prolog_parthood(sub, "abstract_type"),
                "region": self.query_prolog_parthood(sub, "region"),
                "event": self.query_prolog_parthood(sub, "event"),
                "argument": self.query_prolog_parthood(sub, "argument"),
                "action": self.query_prolog_parthood(sub, "action"),
                "set": self.query_prolog_parthood(sub, "set"),
                "time": self.query_prolog_parthood(sub, "time")
            }
            
            inferred_schema = self.evaluate_tree(self.t6, features)
            print(f"📥 Subject Ingested: [{sub}]")
            print(f"   ├── Grounded Abstract Type ──➔ '{features['abstract_type']}'")
            print(f"   └── Parthood Classifier    ──➔ **{inferred_schema}**\n")
            
            t6_facts.append(f"parthood_alignment({sub}, schema_{inferred_schema}).")

        exs_path = os.path.join(self.root_dir, "grigorchuk_planning_space/exs.pl")
        os.makedirs(os.path.dirname(exs_path), exist_ok=True)
        with open(exs_path, "w", encoding="utf-8") as f:
            f.write("%% Autogenerated Intensional Facts Driven by Secondary Parthood Tree Model\n")
            for fact in t6_facts: f.write(f"{fact}\n")

if __name__ == "__main__":
    pipeline = ParthoodInferencePipeline()
    pipeline.run_inference()
