import os
import json
import pickle
import subprocess
import re

class WorldLevelNode:
    def __init__(self, is_leaf=False, split_feature=None, split_value=None, classification=None):
        self.split_feature = split_feature    
        self.split_value = split_value        
        self.is_leaf = is_leaf
        self.classification = classification  
        self.tb = None                        
        self.fb = None                        

class ForestSituationInferencePipeline:
    def __init__(self):
        self.model_dir = "/home/rsherman/projects/SMT-ILP/ZeroVRAM/story_intake_directory/pickled_models"
        self.root_dir = "/home/rsherman/projects/SMT-ILP/ZeroVRAM/Popper-main/examples"
        self.dcg_path = "/home/rsherman/projects/SMT-ILP/ZeroVRAM/popper_workspaces/linguistic_tier1/parser_tier1.pl"
        
        with open(os.path.join(self.model_dir, "level5_plan_synthesis.pkl"), "rb") as f:
            self.t5 = pickle.load(f)

    def query_cross_tree_parthood(self, text_segment):
        clean_text = text_segment.replace("'", "").strip().lower()
        if not clean_text: return "unknown"
        prolog_query = f"consult('{self.dcg_path}'), (part_of('{clean_text}', situation_tree, Concept) -> write(Concept) ; write('unknown')), halt."
        try:
            result = subprocess.run(
                ["swipl", "-q", "-g", prolog_query],
                capture_output=True, text=True, timeout=3
            )
            return result.stdout.strip()
        except Exception:
            return "unknown"

    def evaluate_forest_logic(self, node, feature_vector):
        if node is None: return "unknown"
        if node.is_leaf: return node.classification
        val = feature_vector.get(node.split_feature, "False")
        if str(val) == str(node.split_value): 
            return self.evaluate_forest_logic(node.tb, feature_vector)
        return self.evaluate_forest_logic(node.fb, feature_vector)

    def run_forest_cascade(self):
        print("=" * 95)
        print("🔮 INTENSIONAL INFERENCE SUITE: PARSING UNIVERSAL COGNITIVE FOREST")
        print("=" * 95)
        
        multi_sentence_stories = [
            {"id": "st1_timeline", "narrative_units": ["without a raise", "kept working hard", "request for a raise is refused", "decided to withdraw his effort"]},
            {"id": "sb_timeline_pos", "narrative_units": ["was overwhelmed at work", "tried hard and finished everything", "boss rewarded him"]},
            {"id": "st2_timeline_neg", "narrative_units": ["painful breakup", "attend a party", "anniversary"]},
            # Converted John Reversal Timeline
            {"id": "john_reversal_timeline", "narrative_units": ["planned using several travel events", "missed the amtrak", "reverse his plans and call a cab"]},
            # Converted Sovereign Historical Lifecycles
            {"id": "moses_scripture_timeline", "narrative_units": ["committed murder in egypt", "writing the bible"]},
            {"id": "david_scripture_timeline", "narrative_units": ["losing his illegal son", "going back to being king", "writing the bible"]}
        ]
        
        t5_facts = []
        all_ontology_features = ["stagnate", "diligent", "rejection", "withdraw", "difficulty", "effort", "reward", "grief", "engagement", "success", "planned_trajectory", "edge_deletion", "node_contraction", "decalogue_violation", "path_healing", "scripture_authorship"]

        for story in multi_sentence_stories:
            features = {f: "False" for f in all_ontology_features}
            detected_concepts = []
            for unit in story["narrative_units"]:
                concept = self.query_cross_tree_parthood(unit)
                if concept != "unknown":
                    detected_concepts.append(concept)
                    features[concept] = "True"
            
            inferred_schema = self.evaluate_forest_logic(self.t5, features)
            print(f"📥 Situation ID: [{story['id']}] ──➔ Forest Leaf: **{inferred_schema}**")
            t5_facts.append(f"situation_classification({story['id']}, schema_{inferred_schema}).")

        exs_path = os.path.join(self.root_dir, "grigorchuk_planning_space/exs.pl")
        os.makedirs(os.path.dirname(exs_path), exist_ok=True)
        with open(exs_path, "w", encoding="utf-8") as f:
            f.write("%% Autogenerated Intensional Facts Driven by Interlocking Forest Model\n")
            for fact in t5_facts: f.write(f"{fact}\n")
