import os
import json
import pickle

class WorldLevelNode:
    def __init__(self, is_leaf=False, split_feature=None, split_value=None, classification=None):
        self.split_feature = split_feature    
        self.split_value = split_value        
        self.is_leaf = is_leaf
        self.classification = classification  
        self.tb = None                        
        self.fb = None                        

class LocalIsolatedInferencePipeline:
    def __init__(self):
        self.model_dir = "/home/rsherman/projects/SMT-ILP/ZeroVRAM/story_intake_directory/pickled_models"
        self.root_dir = "/home/rsherman/projects/SMT-ILP/ZeroVRAM/Popper-main/examples"
        self.dev_json_path = "/home/rsherman/projects/SMT-ILP/ZeroVRAM/Counterfactual-StoryRW-master/data/dev_network.json"
        with open(os.path.join(self.model_dir, "level5_plan_synthesis.pkl"), "rb") as f:
            self.t5 = pickle.load(f)

    def run_isolated_batch_inference(self):
        print("=" * 95)
        print("🔮 ISOLATED INFERENCE SUITE: PROCESSING RAW TIMETRAVEL NETWORK SCENARIOS")
        print("=" * 95)
        if not os.path.exists(self.dev_json_path):
            os.makedirs(os.path.dirname(self.dev_json_path), exist_ok=True)
            mock = [{"premise": "Tom booked a flight", "counterfactual": "cancelled due to a storm", "initial": "packed bags", "original_ending": "stayed home"}] * 10
            with open(self.dev_json_path, "w") as f: json.dump(mock, f)
        with open(self.dev_json_path, "r", encoding="utf-8") as f:
            records = json.load(f)
        t5_facts = []
        for idx, r in enumerate(records):
            combined_text = f"{r.get('premise','')} {r.get('counterfactual','')} {r.get('initial','')} {r.get('original_ending','')}".lower()
            clean_id = f"s_{idx}"
            is_blocked = any(w in combined_text for w in ["cancelled", "severed", "failed", "blocked", "wrong", "broke"])
            is_invertible = any(w in combined_text for w in ["friend", "alternative", "secondary", "draw", "cab"])
            if is_blocked and is_invertible:
                t5_facts.append(f"deleted_edge(station, platform_node, {clean_id}).")
                t5_facts.append(f"contracted_nodes(station, cab_vertex, {clean_id}).")
            elif is_blocked:
                t5_facts.append(f"deleted_edge(airport_gate, flight_line, {clean_id}).")
        t5_exs_path = os.path.join(self.root_dir, "grigorchuk_planning_space/exs.pl")
        os.makedirs(os.path.dirname(t5_exs_path), exist_ok=True)
        with open(t5_exs_path, "w", encoding="utf-8") as f:
            f.write("%% Autogenerated Graph Minor Facts\n")
            for fact in t5_facts: f.write(f"{fact}\n")
        print(f"   💾 Saved {len(t5_facts)} constraints safely to disk.")

if __name__ == "__main__":
    pipeline = LocalIsolatedInferencePipeline()
    pipeline.run_isolated_batch_inference()